### ISSUE TITLE
M291 issue in beta3

### ISSUE THREAD

**Issue by T3P3** [dc42/RepRapFirmware#730] opened 2023-04-24 18:08 UTC
https://forum.duet3d.com/topic/32189/3-5-beta3-m291-s-1-error-if-message-box-closed

This macro throws an M292 error if I close the message box using DWC before the T delay times out. The error does not stop the macro from continuing to execute.

m291 s1 t5 P" Message 1: S=1, T=5. 10 second delay before the next message." R"S1 Testing (Close button)"
g4 s10

**Comment by AndyEveritt** [comment] 2023-06-06 21:14
Reproduced in 3.5.0-b3 with macro
```
m291 s1 t5 P" Message 1: S=1, T=5. 10 second delay before the next message." R"S1 Testing (Close button)"
g4 s10
```

Potentially fixed with these changes https://github.com/Duet3D/RepRapFirmware/issues/738

**Comment by AndyEveritt** [comment] 2023-06-11 11:48
This issue is still present in 3.5.0-b4 SBC (standalone not tested yet)

**Comment by AndyEveritt** [comment] 2023-06-11 12:18
Also present in standalone.

Both return the following error
- Standalone:
  - ![image](https://github.com/Duet3D/RepRapFirmware/assets/38423143/288e516a-a353-42ec-801c-22e98a23b710)
- SBC:
  - ![image](https://github.com/Duet3D/RepRapFirmware/assets/38423143/e8e1dc37-21f0-47ee-ae67-47f206b4e0f5)

In both cases the macro was called twice

**Comment by dc42** [comment] 2023-06-12 12:35
@AndyEveritt please post the exact contents of the macro file you used to test this. Did you have a single DWC connection to the Duet, or more than one? Did you also have a PanelDue connected?

**Comment by AndyEveritt** [comment] 2023-06-12 12:36
@dc42
```
m291 s1 t5 P" Message 1: S=1, T=5. 10 second delay before the next message." R"S1 Testing (Close button)"
g4 s10
```

**Comment by dc42** [comment] 2023-07-21 09:15
Reproduced by me, standalone mode, Duet 3 Mini. Disconnecting the PanelDue doesn't change it. If the M291 command is run from the console and the message box closed, no error message appears. However, sending this from the command line does generate the error:

m291 s1 t5 P" Message 1: S=1, T=5. 10 second delay before the next message." R"S1 Testing (Close button)" g4 s10

Looks like DWC sends the M292 command but it doesn't get actioned immediately because the input channel is stuck in the G4 delay command. By the time the delay command expires and the M291 is actioned, the box has timed out.

Ideally we would process the M291 command as soon as it is received even if the input channel is busy in a delay or waiting for moves to complete or in a long macro; however that is difficult to do in the general case. Simplest fix is just to suppress the message.

**Comment by dc42** [comment] 2023-07-21 10:32
Fixed by suppressing the error message.

**Closed as completed by dc42** 2023-07-21 10:32 UTC
Labels: bug
