### ISSUE TITLE
[Bug]: Error in the implementation of M591

### ISSUE THREAD

**Issue by wschadow** [dc42/RepRapFirmware#578] opened 2022-08-01 21:03 UTC
### Duet Forum Discussion Thread

https://forum.duet3d.com/topic/28885/error-in-the-implementation-of-m591?_=1659387146256

### Which Duet products are you using?

- [X] Duet2-Wifi
- [X] Duet2-Ethernet
- [ ] Duet Expansion Breakout Board
- [ ] Duex2
- [ ] Duex5
- [ ] Duet2-Maestro
- [ ] Maestro Dual Driver Expansion
- [ ] Duet3-6HC
- [ ] Duet3-3HC
- [ ] Duet3-1XD
- [ ] Duet3-1LC
- [ ] Duet3-Tool Distribution Board
- [X] Duet3-Mini5+
- [ ] Duet3-Mini2+
- [ ] Raspberry Pi or other SBC
- [ ] SmartEffector
- [ ] Magnetic Filament Sensor
- [ ] Laser Filament Sensor
- [ ] PT100 Daughterboard
- [ ] Thermocouple Daughterboard
- [ ] PanelDue
- [ ] Other
- [ ] None

### Firmware Version

3.4.0, 3.4.1

### Duet Web Control Version

DWC 3.4.0, 3.4.1

### Are you using a Single Board Computer (RaspberryPi) with your Duet?

- [ ] Yes I use a SBC.
- [X] No I do not use a SBC.

### Please upload the results of sending M122 in the gcode console.

```shell
=== Diagnostics ===
RepRapFirmware for Duet 2 WiFi/Ethernet version 3.4.2rc1 (2022-07-06 16:21:02) running on Duet WiFi 1.02 or later
Board ID: 0JD0M-9P6B2-NJ4S4-6JKF4-3S86P-9A16L
Used output buffers: 3 of 26 (21 max)
=== RTOS ===
Static ram: 23860
Dynamic ram: 75924 of which 0 recycled
Never used RAM 9296, free system stack 126 words
Tasks: NETWORK(ready,54.2%,237) HEAT(notifyWait,0.8%,333) Move(notifyWait,0.1%,298) MAIN(running,44.2%,440) IDLE(ready,0.6%,30), total 100.0%
Owned mutexes: WiFi(NETWORK)
=== Platform ===
Last reset 22:20:26 ago, cause: software
Last software reset at 2022-08-01 00:36, reason: User, GCodes spinning, available RAM 9364, slot 1
Software reset code 0x0003 HFSR 0x00000000 CFSR 0x00000000 ICSR 0x00417000 BFAR 0xe000ed38 SP 0x00000000 Task MAIN Freestk 0 n/a
Error status: 0x00
Aux0 errors 0,0,0
Step timer max interval 0
MCU temperature: min 34.3, current 35.8, max 37.9
Supply voltage: min 23.8, current 24.0, max 24.4, under voltage events: 0, over voltage events: 0, power good: yes
Heap OK, handles allocated/used 99/4, heap memory allocated/used/recyclable 2048/1204/1126, gc cycles 590
Events: 0 queued, 0 completed
Driver 0: standstill, SG min 0
Driver 1: standstill, SG min 0
Driver 2: standstill, SG min 0
Driver 3: standstill, SG min n/a
Driver 4: standstill, SG min 0
Driver 5: 
Driver 6: 
Driver 7: 
Driver 8: 
Driver 9: 
Driver 10: 
Driver 11: 
Date/time: 2022-08-01 22:56:38
Cache data hit count 4294967295
Slowest loop: 9.06ms; fastest: 0.09ms
I2C nak errors 0, send timeouts 0, receive timeouts 0, finishTimeouts 0, resets 0
=== Storage ===
Free file entries: 10
SD card 0 detected, interface speed: 20.0MBytes/sec
SD card longest read time 3.9ms, write time 2.6ms, max retries 0
=== Move ===
DMs created 83, segments created 6, maxWait 665458ms, bed compensation in use: none, comp offset 0.000
=== MainDDARing ===
Scheduled moves 51, completed 51, hiccups 0, stepErrors 0, LaErrors 0, Underruns [0, 0, 0], CDDA state -1
=== AuxDDARing ===
Scheduled moves 0, completed 0, hiccups 0, stepErrors 0, LaErrors 0, Underruns [0, 0, 0], CDDA state -1
=== Heat ===
Bed heaters 0 -1 -1 -1, chamber heaters -1 -1 -1 -1, ordering errs 0
=== GCodes ===
Segments left: 0
Movement lock held by null
HTTP is idle in state(s) 0
Telnet is idle in state(s) 0
File is idle in state(s) 0
USB is idle in state(s) 0
Aux is idle in state(s) 0
Trigger is idle in state(s) 0
Queue is idle in state(s) 0
LCD is idle in state(s) 0
Daemon is idle in state(s) 0
Autopause is idle in state(s) 0
Code queue is empty
=== Network ===
Slowest loop: 41.09ms; fastest: 0.00ms
Responder states: HTTP(0) HTTP(0) HTTP(0) HTTP(0) FTP(0) Telnet(0), 0 sessions
HTTP sessions: 1 of 8
- WiFi -
Network state is active
WiFi module is connected to access point 
Failed messages: pending 0, notready 0, noresp 0
WiFi firmware version 1.26
WiFi MAC address 48:3f:da:a6:ef:7b
WiFi Vcc 3.35, reset reason Power up
WiFi flash size 2097152, free heap 23560
WiFi IP address 192.168.2.56
WiFi signal strength -46dBm, mode 802.11n, reconnections 0, sleep mode modem
Clock register 00002002
Socket states: 0 0 0 0 0 0 0 0
```

### Please upload the content of your config.g file.

```gcode
; =========================================================================================================
;
; Configuration file for Duet2-WiFi/Ethernet (firmware version 3.4 and higher)
;
; for 0.9° motors on xy, and 0.9° or 1.8° (only LGXM) motor e
;
; for Caribou420 Duet2 WiFi/Ethernet LGX Mosquito - E3d or SE Thermistor - SuperPINDA
;
; CariboDuetConfiguration Release : "2.0.0-RC2"
;                           Build :   360
;
; Copyright Caribou Research & Development 2022. Licensed under GPL3. No commercial use.
; Source code and release notes are available on github: https://github.com/Caribou3d/CaribouDuet2-ConfigurationMacros
;
;
; =========================================================================================================
;
; global variables
;
global IdleCounter = 0                                                 ; counts idle time
global ExtruderTempActive_Old = 0                                      ; stores extruder temperature for idle check
global BedTempActive_Old = 0                                           ; stores bed temperature for idle check
global OldStateStatus = 0                                              ; stores teh satus processing = 1
;
; general settings
;
M111 S0 					                                           ; debugging off
G21 					                                               ; work in millimetres
;
; =========================================================================================================
; network settings
; =========================================================================================================
;
M550 P"Caribou420-LGXM18-NSP"                                          ; set printer name
;
M552 S1                                                                ; enable network
M586 P0 S1                                                             ; enable HTTP
M586 P1 S1                                                             ; enable FTP
M586 P2 S0                                                             ; disable Telnet
M575 P1 S1 B57600                                                      ; enable support for PanelDue
;
; =========================================================================================================
; drives
; =========================================================================================================
;
M569 P0 S0 F11                                                         ; physical drive 0 goes backwards - x axis
M569 P1 S0 F8 Y3:2                                                     ; physical drive 1 goes backwards - y axis
M569 P2 S0 F10                                                         ; physical drive 2 goes backwards - z axis left
M569 P3 S1 F14                                                         ; physical drive 3 goes forwards  - extruder
M569 P4 S0 F10                                                         ; physical drive 4 goes backwards - z axis right
;
; motor configuration
;
M584 X0 Y1 Z2:4 E3                                                     ; set drive mapping
M671 X-36.5:293.5 Y0:0 S1.00                                           ; leadscrews at left (connected to Z/drive 2) and right (connected to E1/drive 4) of x axis
;
; set microsteps and steps / mm
; =========================================================================================================
;
M350 X16 Y16 Z16 E16 I1                                                ; configure microstepping with interpolation
M92 X200.00 Y200.00 Z400.00 E400.00                                    ; set steps per mm
;
; set motor currents
; =========================================================================================================
;
M906 X1250 Y1250 Z650 E650 I40                                         ; set motor currents (mA) and motor idle factor in percent
;
M84 S60                                                                ; set idle timeout
;
; set speeds
; =========================================================================================================
;
M201 X500.00 Y500.00 Z100.00 E500.00                                   ; set accelerations (mm/s^2)
M203 X12000.00 Y12000.00 Z1000.00 E3600.00                             ; set maximum speeds (mm/min)
M204 P500.0 T500.0                                                     ; set print and travel accelerations (mm(s^2)
M566 X480.00 Y480.00 Z48.00 E300.00                                    ; set maximum instantaneous speed changes (mm/min)
;
M564 H0                                                                ; allow unhomed movement
;
; =========================================================================================================
; axes limits
; =========================================================================================================
;
M208 X-2 Y-7.5 Z0 S1                                                   ; set axes minimum
M208 X254.6 Y214 Z416.50 S0                                            ; set axes maximum
;
; =========================================================================================================
; endstops
; =========================================================================================================
;
M574 X1 S3                                                             ; configure sensorless endstop for low end on x
M574 Y1 S3                                                             ; configure sensorless endstop for low end on y
M574 Z1 S2                                                             ; configure z-probe endstop for low end on z
M574 Z2 S3                                                             ; configure sensorless endstop for high end on z
;
; =========================================================================================================
;
; SuperPINDA
;
M558 P5 C"^zprobe.in" H1.5 F600 T8000 A3 S0.03                         ; set z probe to SuperPINDA
M557 X23:235 Y5:186 S30.25:30                                          ; define mesh grid
;
; =========================================================================================================
;
M574 Z1 S2                                                             ; set endstops controlled by probe
;
; stallguard sensitivy
;
M915 X S2 F0 H400 R0                                                   ; set x axis sensitivity
M915 Y S1 F0 H400 R0                                                   ; set y axis sensitivity
M915 Z S0 F0 H200 R0                                                   ; set z axis sensitivity
;
; =========================================================================================================
; heaters, fans, thermistors
; =========================================================================================================
;
; heated bed
; =========================================================================================================
;
M308 S0 P"bedtemp" Y"thermistor" T100000 B4138 R4700 A"Bed"            ; configure sensor 0 as thermistor on pin bedtemp
M950 H0 C"bedheat" Q50 T0                                              ; create bed heater output on bedheat and map it to sensor 0
M143 H0 S110                                                           ; set temperature limit for heater 0 to 110°C
M307 H0 B0 S1.00                                                       ; disable bang-bang mode for the bed heater and set PWM limit
M140 H0                                                                ; map heated bed to heater 0
;
; extruder
; =========================================================================================================
;
; hotend (Mosquito or Mosquito Magnum with E3d Thermistor)
;
M308 S1 P"e0temp" Y"thermistor" T100000 B4725 C7.060000e-8 A"Nozzle E1"; E3d configure sensor 0 as thermistor on pin e0temp
;
M950 H1 C"e0heat" T1                                                   ; create nozzle heater output on e0heat and map it to sensor 1
M307 H1 B0 S1.00                                                       ; disable bang-bang mode for heater 1 and set PWM limit
M143 H1 S280                                                           ; set temperature limit for heater 1 to 280°C
;
; display MCU and drivers temperature
; =========================================================================================================
;
M308 S4 P"mcu-temp" Y"mcu-temp" A"MCU"                                 ; set virtual heater for MCU
M308 S5 P"drivers" Y"drivers" A"Driver"                                ; set virtual heater for stepper drivers
;
; fans
; =========================================================================================================
;
; radial fan
;
M950 F0 C"fan0" Q160                                                   ; create fan 0 on pin fan1 and set its frequency
M106 P0 S0 H-1                                                         ; set fan 0 value. Thermostatic control is turned off
;
; extruder fan (temperature controlled)
;
M950 F1 C"fan1" Q500                                                   ; create fan 1 on pin fan0 and set its frequency
M106 P1 H1 T45                                                         ; fan turns on at 45°C
;
; ========================================================================================================
; tools
; =========================================================================================================
;
M563 P0 D0 H1 F0                                                       ; define tool 0
G10 P0 X0 Y0 Z0                                                        ; set tool 0 axis offsets
M568 P0 S0 R0 A0                                                       ; turn off extruder
M302 S180 R180                                                         ; allow extrusion starting from 180°C and retractions already from 180°C
;
; =========================================================================================================
; other settings
; =========================================================================================================
;
M18 XY                                                                 ; release / unlock x, y
M501                                                                   ; use config-override (for Thermistor Parameters and other settings)
G90                                                                    ; send absolute coordinates...
M83                                                                    ; ... but relative extruder moves
;
; =========================================================================================================
; filament handling
; =========================================================================================================
;
; execute macros that determine the status of the filament sensor
;
M98 P"0:/sys/00-Functions/FilamentsensorStatus"
;
; =========================================================================================================
;
; offsets - place off-sets for x and y here. z-offsets are handled in the print sheet macros
;
G31 P1000 X23 Y5
;
; =========================================================================================================
;
```

### What happened?

The documentation of M591 says that an event is created and that filament-error.g will be executed if present. Only if not present the default action is taken (Pause print using pause.g and inform user via message box). I noticed that the message box always opens when an "error" occurs.

My expectation would be that when you "catch" the error in filament-error.g the window should not pop-up.

More general it must not be an "error", it could be just an "event". When you invert the sensor P1 <-> P2 is can can in autoload or run-out mode. As a work around I use the sensor as a trigger when in autoload mode, and a sfilament sensor when in run-out mode. This is working nicely but when trying to evaluate the status of the sensor and no filament is loaded the info window pos-up.

The sensor is configured as M591 D0 P1 C"e0stop" S1. In my case it will trigger when filament is inserted.

This is what happens, when filament is inserted. First on the Panel first the error message pops-up:

![f1](https://user-images.githubusercontent.com/25696872/182245960-75c818ff-71b4-4338-a619-178c3edd3fe7.jpg)

Then a split secend later the message from filament-error.g pops-up:

![f2](https://user-images.githubusercontent.com/25696872/182246147-2f3fb20f-b97b-4b5e-9d87-d0aac2098969.jpg)

The console looks like this:

![f3](https://user-images.githubusercontent.com/25696872/182246228-dc14091b-f215-46ad-9f7a-2e9c0afac0b8.jpg)

**Comment by dc42** [comment] 2022-11-26 08:30
I believe this was fixed in release 3.4.2. Please re-test using RRF 3.4.4 and re-open this issue if the problem is still present.

**Closed as completed by dc42** 2022-11-26 08:30 UTC
Labels: bug
