### ISSUE TITLE
File uploads through web interface sometimes hang at 100%

### ISSUE THREAD

**Issue by crispy1066** [dc42/RepRapFirmware#22] opened 2015-12-15 03:15 UTC
Possible theory is it's expecting more data than really exists.  My guess is webserver.cpp lines 500-660.

**Comment by shadow651** [comment] 2015-12-15 22:00
I can also confirm that I occasionally experience this issue.
I typically cancel the upload and restart; it usually works the second time.

**Comment by criticallimit** [comment] 2015-12-18 21:54
I can confirm this too.
It happens to me nearly every upload bigger than 3GB. Sometimes it works at the second try, but most of the time it stops completely at no special percentage. After that there are no files shown on the card anymore in the webserver. Only reset helps.

**Comment by dc42** [comment] 2015-12-27 21:23
Please try version 1.09o.

**Comment by criticallimit** [comment] 2015-12-28 16:43
new version made it worse.
No files are uploaded now to the end. All files that I´m uploading stuck at no specific percentage.
Only very small files are going through. But files bigger than 10MB are stucking. Most of my files are 20-100MB.

**Comment by dc42** [comment] 2015-12-28 17:48
Thanks for your feedback. I have had one other report of a similar problem and I will do further testing over the next few days. Meanwhile I suggest you either try a different SD card, or revert to 1.09m.

On 28 December 2015 16:43:51 GMT+00:00, criticallimit <notifications@github.com> wrote:
>new version made it worse.
>No files are uploaded now to the end. All files that I´m uploading
>stuck at no specific percentage.
>Only very small files are going through. But files bigger than 10MB are
>stucking. Most of my files are 20-100MB. 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/dc42/RepRapFirmware/issues/22#issuecomment-167601279

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by criticallimit** [comment] 2015-12-28 18:06
Have tested it with 5 different SD cards now which are working fine in all other hardware (phone, smoothie, camera etc). None of them working in the duet. But I think it´s not a SD card problem. It´s the webserver.

**Comment by W3DRK** [comment] 2016-01-18 18:01
Just had this happen yesterday with 1.09r on a Duet v0.6.  After two failed attempts, I re-homed all axis and it worked fine.  Coincidence?

**Comment by tomasf** [comment] 2016-02-15 09:42
I've often seen this one, too. I now upload everything over FTP, which works much better.

**Comment by dc42** [comment] 2016-02-15 12:31
It would be helpful if you can supply a Wireshark trace of a failed upload.

David Crocker, Escher Technologies Ltd.
http://www.eschertech.com
Tel. +44 (0)20 8144 3265 or +44 (0)7977 211486

**Comment by WZ9V** [comment] 2016-02-15 12:48
i noticed similar problems last night when I was manually calibrating using the web tool over a three hour period.  At various times I would get errors which are hard to reproduce.

AJAX timeout (reconnect usually fixed it)
File upload lockout (retry after disconnect/reconnect usually fixed it)
Web interface looking connected but no g-code works (disconnect/reconnect usually fixed it)

I was using Firefox on Linux Mint and it had some recent updates that make me wonder if it's browser issues. I'll try Chrome today and see if it's better.

**Comment by dc42** [comment] 2016-12-20 10:10
There have been numerous improvements to the network code since this report was filed and I have had no reports of this issue in recent months. So I am closing it. Feel free to re-open it if you experience it using firmware 1.16 with DWC 1.13, or later versions.

**Closed by dc42** 2016-12-20 10:10 UTC
