### ISSUE TITLE
G1 H1 E moves not working in 3.5.0-beta.3

### ISSUE THREAD

**Issue by dc42** [dc42/RepRapFirmware#847] opened 2023-05-10 15:12 UTC
### Duet Forum Discussion Thread

https://forum.duet3d.com/topic/32153/m915-feature-is-loss-after-3-5-0-beta2-version-on-extruder

G1 H1 E moves no longer work.

**Comment by dc42** [comment] 2023-05-10 15:14
See https://github.com/Duet3D/RepRapFirmware/pull/843 for a user-suggested fix.

**Comment by dc42** [comment] 2023-05-24 15:50
Worked around this by disabling the cold extrusion check for special moves in DDA.cpp.

**Comment by alexjx** [comment] 2023-06-17 09:30
@dc42 David, you might be influenced by my patch. It seems that following code is incorrect. We should allow checkEnstop moves instead of skip it.

My testing of the latest 3.5.0 beta4 shows it's not working as intended

```cpp
	// Check for cold extrusion/retraction. Do this now because we can't read temperatures from within the step ISR, also this works for CAN-connected extruders.
	// Don't check if it is a special move (indicated by flags.checkEndstops) because the 'tool' variable isn't valid for those moves
	if (!flags.checkEndstops || Tool::ExtruderMovementAllowed(tool, directionVector[drive] > 0, extruder))
	{
```

which should be 

```cpp
	// Check for cold extrusion/retraction. Do this now because we can't read temperatures from within the step ISR, also this works for CAN-connected extruders.
	// Don't check if it is a special move (indicated by flags.checkEndstops) because the 'tool' variable isn't valid for those moves
	if (flags.checkEndstops || Tool::ExtruderMovementAllowed(tool, directionVector[drive] > 0, extruder))
	{
```

**Comment by dc42** [comment] 2023-06-18 20:44
Thanks @alexjx, I will fix this in the next commit.

**Comment by T3P3** [comment] 2023-08-02 15:23
@alexjx please can you test to se eif this is now working for you in RRF 3.5.0-beta4

**Comment by alexjx** [comment] 2023-08-07 13:12
@T3P3 I'm sorry, I dont have access to my printers in this two weeks. Can it wait till end of this weekend?

**Comment by T3P3** [comment] 2023-08-07 13:17
Plase test and let us know as soon as you can, we may release the next beta/rc1 in between.

**Comment by alexjx** [comment] 2023-08-07 13:34
OK, I will give it a try by this Sunday.

**Comment by alexjx** [comment] 2023-08-14 00:58
@T3P3 I could confirm this works in latest 3.5-dev branch.

**Comment by T3P3** [comment] 2023-08-14 08:55
Thanks, will close this as fixed

**Closed as completed by T3P3** 2023-08-14 08:55 UTC
Labels: bug, Done - Needs Testing
