### ISSUE TITLE
[FeatureRequest]: M591 filament monitoring option for USB control

### ISSUE THREAD

**Issue by jaysuk** [dc42/RepRapFirmware#862] opened 2023-06-06 08:20 UTC
### Is your feature request related to a problem? Please describe.

See this thread https://forum.duet3d.com/topic/31221/filament-monitoring-while-printing-via-usb?_=1685740576518

### Describe the solution you propose.

See the above thread

### Describe alternatives you've considered

Ex. A workaround exists but it is tedius, for example...

### Provide any additional context or information.

Ex. Photos, mockups, etc.

**Comment by jaysuk** [comment] 2023-06-06 08:31
and also see here https://forum.duet3d.com/topic/32626/rotating-magnet-filament-sensor-with-external-print/5

**Comment by jaysuk** [comment] 2023-06-06 09:27
also, implementing host action commands from Marlin may give the best compatibility to existing server control software https://marlinfw.org/docs/configuration/configuration.html#host-action-commands

**Comment by chrishamm** [comment] 2023-06-06 10:05
This isn't a high priority at the moment. It should be already possible to develop a work-around using `daemon.g` and something like this:

```
var hadFilamentError = false
while true
  G4 S1 ; check once per second
  if sensors.filamentMonitors[0].status != "ok"
    if !var.hadFilamentError
      M118 S"Filament error! Do something."
      set var.hadFilamentError = true
  else
    set var.hadFilamentError = false
```

Note that I have not tested this macro yet.

**Comment by T3P3** [comment] 2023-08-16 14:48
@jay please can you have a look at this and see if its working for you now.

**Comment by dc42** [comment] 2023-08-25 16:09
Issues to be resolved:
- The response to M591 D# by itself doesn't distinguish between enable modes 1 and 2 (now fixed)
- There was a use of = where == was intended, that GCC did not pick up (now fixed)
- Although the code that calls the filament monitor Check or Clear function takes account of the enable mode in both RRF and Duet3Expansion, the subsequent code in RRF still checks if we are really printing before raising an event. To account properly for the enable mode, RRF will need to keep track of the enable mode of remote filament monitors, or the enable mode will need to be included in the CAN message that passes filament monitor status back to the main board. We could possibly include the filament sensor enable mode in the 'extra' field of the reply to the configuration message.

**Comment by dc42** [comment] 2023-08-25 16:33
Now fixed and tested.

**Closed as completed by dc42** 2023-08-25 16:33 UTC
Labels: enhancement
