### ISSUE TITLE
Add MaxPortsPerHeater limit to OM

### ISSUE THREAD

**Issue by droftarts** [dc42/RepRapFirmware#816] opened 2023-05-03 13:59 UTC
### Is your feature request related to a problem? Please describe.

MaxPortsPerHeater is missing from limits section of OM.

### Describe the solution you propose.

Add MaxPortsPerHeater to OM

### Describe alternatives you've considered

NA

### Provide any additional context or information.

NA

**Comment by dc42** [comment] 2023-05-03 17:07
Duplicate of #809.

**Closed as completed by dc42** 2023-05-03 17:07 UTC
Labels: enhancement, Object Model
